/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmad Dimas Abid M
 */
public class verifikasi extends javax.swing.JFrame {

    int tmp;
    int ambil;
    /**
     * Creates new form verifikasi
     */
    public verifikasi(int e, String k, String b, String n, String t, int u) {
        initComponents();
        this.tmp = e;
        this.ambil = u;
        if(k.equals("000")){
            kode.setText("009");
        } else {
            kode.setText(k);
        }
        bank.setText(b);
        rekening.setText(n);
        transfer.setText("Rp "+t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bank = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        transfer = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kode = new javax.swing.JLabel();
        rekening = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bank Tujuan  :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 170, 130, 30);

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setText("<--  SALAH");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 310, 130, 40);

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Verifikasi Data");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 10, 200, 40);

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Salah Untuk Mengulangi Transfer");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 70, 290, 40);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. Rekening  :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 210, 110, 30);

        bank.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        bank.setForeground(new java.awt.Color(255, 255, 255));
        bank.setText(".");
        jPanel1.add(bank);
        bank.setBounds(210, 170, 160, 30);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jumlah Transfer  :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 250, 140, 30);

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kode Bank  :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 130, 100, 30);

        transfer.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        transfer.setForeground(new java.awt.Color(255, 255, 255));
        transfer.setText(".");
        jPanel1.add(transfer);
        transfer.setBounds(210, 250, 110, 30);

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Tekan Benar Jika Benar, Tekan");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(120, 40, 280, 40);

        jLabel13.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tekan Benar Jika Benar, Tekan");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(120, 40, 310, 40);

        kode.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        kode.setForeground(new java.awt.Color(255, 255, 255));
        kode.setText(".");
        jPanel1.add(kode);
        kode.setBounds(210, 130, 110, 30);

        rekening.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        rekening.setForeground(new java.awt.Color(255, 255, 255));
        rekening.setText(".");
        jPanel1.add(rekening);
        rekening.setBounds(210, 210, 110, 30);

        jButton5.setBackground(new java.awt.Color(51, 255, 102));
        jButton5.setText("BENAR  -->");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(350, 310, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 370);

        setBounds(0, 0, 516, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new pilihTransfer(tmp).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        tmp -= ambil;
        new berhasil(tmp).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bank;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kode;
    private javax.swing.JLabel rekening;
    private javax.swing.JLabel transfer;
    // End of variables declaration//GEN-END:variables
}
